# Generated by Ansible
MARIADB_PASSWORD={{ mariadb_root_password }}

POSTGRES_PASSWORD={{ postgres_password }}
POSTGRES_USER={{ postgres_user }}
POSTGRES_DB={{ postgres_db }}

MONGO_ROOT_USERNAME={{ mongo_root_username }}
MONGO_ROOT_PASSWORD={{ mongo_root_password }}

# Authentik
AUTHENTIK_DB_USER={{ db_app_user }}
AUTHENTIK_DB_NAME=authentik_db
AUTHENTIK_SECRET_KEY=cjd5z+HoWSHja0aUKT9LsmE0Q/3ZY20gmOj3IJVcEWw=
