[db_servidores]
# Opción 1: Si ejecutas el playbook DENTRO de este mismo servidor:
localhost ansible_connection=local

# Opción 2: Si ejecutas el playbook DESDE AFUERA (ej. desde tu PC):
# nodo-db-core ansible_host=100.79.126.31 ansible_user=root
