---
- name: Instalación y Configuración Automática de Nodo DB Core
  hosts: all
  become: yes
  tasks:
    - name: FASE 1 - Instalacion de Docker y dependencias
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
          - curl
          - git
        state: present
        update_cache: yes

    - name: FASE 2 - Creacion de carpetas de datos con permisos base
      file:
        path: "/opt/servicios/nodo-db-core/{{ item }}"
        state: directory
        mode: '0755'
        owner: "1000"
        group: "1000"
      with_items:
        - db_data
        - mongo_data
        - configs/postgres

    - name: FASE 2.1 - Estructura jerárquica de backups
      file:
        path: "/opt/servicios/nodo-db-core/backups/{{ item }}"
        state: directory
        mode: '0755'
        owner: "1000"
        group: "1000"
        recurse: yes
      with_items:
        - mariadb/wordpress
        - mariadb/glpi
        - postgres/n8n
        - postgres/zabbix
        - mongo

    - name: FASE 3 - Permisos especificos para Postgres
      file:
        path: "/opt/servicios/nodo-db-core/postgres_data"
        state: directory
        owner: "70"
        group: "70"
        mode: '0700'

    - name: FASE 4 - Sincronizar Inicialización
      # Esto copia el script que crea la DB de Zabbix antes de que encienda el motor
      copy:
        src: "../configs/postgres/"
        dest: "/opt/servicios/nodo-db-core/configs/postgres/"
        mode: '0644'

    - name: FASE 5 - Pull de imagenes
      shell: "docker pull {{ item }}"
      with_items:
        - "mariadb:11.4"
        - "postgres:18-alpine"
        - "mongo:latest"

    - name: FASE 6 - Levantar los contenedores
      shell: "cd /opt/servicios/nodo-db-core && docker compose up -d"
